config/routes.rb
Minercloud::Application.routes.draw do
  
  devise_for :users
  
  resources :workers, :only => [:new, :create, :show]
  resources :users, :only => [:show]

  root :to => "pages#home"

end

app/models/block.rb
class Block < ActiveRecord::Base
end

app/models/share.rb
class Share < ActiveRecord::Base
  belongs_to :worker
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_many :workers
end

app/models/worker.rb
class Worker < ActiveRecord::Base
  belongs_to :user
  has_many :shares

  validates :username, :presence => true,
                       :uniqueness => {:case_sensitive => false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource)
    stored_location_for(:user) || root_path # could be user_path(current_user.id)   if you want to redirect to the user page
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end

end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_filter :authenticate_user!, :only => [:index]
  
  def index
    @shares = Share.all
    
    respond_to do |format|
      format.html #index.html.erb
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:show]
  before_filter :correct_user, :only => [:show]

  def show
    @user = current_user
    @workers = current_user.workers

    respond_to do |format|
      format.html #index.html.erb
    end
  end

  private

    def correct_user                 #will make sure the signed_in user is the one trying to access his own page and not elses
        @user = User.find(params[:id])
        redirect_to(root_path) unless current_user?(@user)
    end

    def current_user?(user)
      user == current_user
    end

end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_filter :authenticate_user!, :only => [:index, :create]

  def index
    @workers = current_user.workers
    
    respond_to do |format|
      format.html #index.html.erb
    end
  end

  def create
    @worker = current_user.workers.build(params[:worker])
    if @worker.save
      redirect_to current_user, :flash => {:success => "New worker created!"}
    else
      render "new"
    end
  end

  def show
    @found_worker = Worker.find(params[:id])
    if current_user.workers.exists?(@found_worker)
      @worker = @found_worker
      respond_to do |format|
        format.html
      end
    else
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo
    image_tag("gold.png", :alt => "minercloud.com", :class => "round")
  end

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", %></li>
      <li><%= link_to "Ruby On Rails", 'http://rubyonrails.org/'%></li>
      <li><%= link_to "Blueprint", 'http://www.blueprintcss.org/'%></li>
    </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class = "round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
        <li><%= link_to "My Account", user_path(current_user)%></li>
      <%end%>
      <li><%= link_to "Help" %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Sign out",  destroy_user_session_path%></li>
      <%else%>
        <li><%= link_to "Sign in",  new_user_session_path%></li>
      <%end%>
    </ul>
  </nav>
</header>

app/views/layouts/_stylsheets.html.erb
<!--[if lt IE 9]> 
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script> 
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'%>
<%= stylesheet_link_tag 'blueprint/screen', :media => 'print'%>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minercloud</title>
    <%= csrf_meta_tag %>
    <%= render "layouts/stylsheets"%>
    <%= javascript_include_tag :defaults%>
  </head>
  <body>
  <div class="container">
    <%= render "layouts/header"%>
    <section class="round">
      <%= yield %>
    </section>
    <%= render "layouts/footer"%>
    <%= debug(params) if Rails.env.development?%>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<h2>Home</h2>

app/views/shares/_share.haml
%tr
  %td= share.created_at
  %td= share.rem_host
  %td= share.our_result
  %td= share.upstream_result
  %td= share.reason
  %td= share.solution

app/views/shares/index.haml
%h1 Listing Shares

%table
  %tr
    %th Created At
    %th Rem Host
    %th Our Result
    %th Upstream Result
    %th Reason
    %th Solution
  - @shares.each do |share|
    %tr
      %td= share.created_at
      %td= share.worker_id
      %th= share.rem_host
      %th= share.our_result
      %th= share.upstream_result
      %th= share.reason
      %th= share.solution

app/views/users/show.haml
%h1= @user.email

%h3 All your workers...
%table
   %th Worker
   %th Password
   = render @workers

= button_to "Create new worker...", new_worker_path, :method => :get

app/views/workers/_worker.haml
%tr
  %td= link_to worker.username, worker_path(worker)
  %td= worker.password

app/views/workers/index.haml
%h1 Your Workers

%table
  %tr
    %th Username
    %th Password
  - @workers.each do |worker|
    %tr
      %td= worker.username
      %td= worker.password

= button_to "Create new worker...", new_worker_path, :method => :get

app/views/workers/new.html.erb
<h2>Create a worker..</h2>

<%= form_for :worker, :url => {:action => "create"}  do |f|%>
  <%=f.label :username%> </br>
  <%=f.text_field :username%> </br>

  <%=f.label :password%> </br>
  <%=f.text_field :password%>  </br>

  <%=f.submit "Create Worker"%>
<%end%>

app/views/workers/show.haml
%h1= @worker.username


%h3 Shares

%table
  %tr
    %th Created At
    %th Worker ID
    %th Rem Host
    %th Our Result
    %th Upstream Result
    %th Reason
    %th Solution
    = render @worker.shares